server.port=8079
spring.application.name=proxy-service
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway discovery
# spring.cloud.gateway.discovery.locator.enabled=
# spring.cloud.gateway.discovery.locator.lower-case-service-id=false

# CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173,http://localhost:8079
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=Authorization,Content-Type
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true




# server.port=8079
# #connexion sur eureka
# #eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# eureka.client.service-url.defaultZone=http://registry-service:8761/eureka/
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true
# #decouverte dynamique des routes
# spring.cloud.gateway.discovery.locator.enabled=true

#server.port=8079
#connexion sur eureka
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true
# #decouverte dynamique des routes
# spring.cloud.gateway.discovery.locator.enabled=true


# server.port=8079
# eureka.client.service-url.defaultZone=http://bank-registry-service:8761/eureka/
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true
# spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# spring.cloud.discovery.enabled=true